import turtle #imported turtle and time 
import time

turtle.Turtle()
window = turtle.Screen()
window.setup (width=1.0, height=1.0, startx=0, starty=0)
turtle.pensize(1)
turtle.shape("turtle")


#This function shows the splash page 
def main():
    turtle.color('red')
    turtle.penup()
    turtle.goto(0,250)
    turtle.pendown()
    turtle.write("Midterm Project", font=("Courier",30,'italic'),align='center')
    turtle.right(90)
    turtle.penup()
    turtle.fd(50)
    turtle.pendown()
    turtle.write("The Gemini Constellation", font=("Courier",30,'italic'),align='center')
    turtle.penup()
    turtle.fd(50)
    turtle.pendown()
    turtle.write("Laxmi Gurung", font=("Courier",30,'italic'),align='center')
    
main()

time.sleep(10)#Here page will be displayed for 10 seconds
turtle.clear()#this clears the window

#In this function the second page displays, could only import gif images
def image():
    window.bgpic('gemini.gif')
    time.sleep(10)
image()

window.clear()

#In this function, the constellation appears in white background
def constellation():
   
    #moved the turtle to top left of the page to start.
    turtle.bgcolor('white')
    turtle.color('black')
    turtle.penup()
    turtle.left(20)
    turtle.fd(40)
    turtle.left(30)
    turtle.fd(300)
    turtle.pendown()
    turtle.left(205)

    #main diagram begins
    turtle.write("Castor")
    turtle.dot(18)
    turtle.fd(50)
    turtle.dot(12)
    turtle.right(15)
    turtle.fd(100)
    turtle.dot(12)
    turtle.left(80)
    turtle.fd(130)
    turtle.dot(12)
    turtle.penup()
    turtle.back(130)
    turtle.pendown()
    turtle.right(90)
    turtle.fd(140)
    turtle.write("Mebsuta")
    turtle.dot(12)
    turtle.right(25)
    turtle.fd(120)
    turtle.dot(12)
    turtle.penup()
    turtle.back(120)
    turtle.pendown()
    turtle.left(45)
    turtle.fd(100)
    turtle.dot(12)
    turtle.left(30)
    turtle.fd(45)
    turtle.write("Tejat Posterior")
    turtle.dot(12)
    turtle.left(15)
    turtle.fd(80)
    turtle.write("Propus")
    turtle.dot(12)
    #From here going to draw the twins

    turtle.penup()
    turtle.back(200)
    turtle.right(70)
    turtle.back(190)
    turtle.right(120)
    turtle.fd(30)
    turtle.left(40)
    turtle.back(45)
    turtle.right(25)
    turtle.down()
    turtle.fd(70)
    turtle.dot(12)
    turtle.right(20)
    turtle.fd(50)
    turtle.dot(12)
    turtle.right(40)
    turtle.fd(50)
    turtle.write("Pollux")
    turtle.dot(18)
    turtle.back(50)
    turtle.left(90)
    turtle.fd(40)
    turtle.dot(12)
    turtle.back(40)
    turtle.left(70)
    turtle.fd(100)
    turtle.write("Wassat")
    turtle.dot(12)
    turtle.right(30)
    turtle.fd(100)
    turtle.dot(12)
    turtle.left(40)
    turtle.fd(180)
    turtle.write("Alzirr")
    turtle.dot(12)
    turtle.pu()
    turtle.back(180)
    turtle.right(40)
    turtle.back(100)
    turtle.pd()
    turtle.left(60)
    turtle.fd(90)

    turtle.dot(12)
    turtle.right(25)
    turtle.fd(120)
    turtle.write("Ahena")
    turtle.dot(15)
    turtle.penup()
    # Writing the Logo
    turtle.goto(-300,250)
    turtle.write("The Gemini Constellation",font=("Courier",10,'italic'))

constellation()
time.sleep(10)
window.clear()

#In this function the dots appears before and the lines get connected after wards
def upgrade():
    window.bgpic('night.gif')
    turtle.color('white')
    time.sleep(2)
    turtle.penup()
    turtle.goto(50, -20)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(20,50)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(80,45)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(120, 80)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-120, 90)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-100, 120)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-140, 50)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-160, 20)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-200, 80)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-220, 50)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-220, -50)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-120, -80)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-100, -120)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-40, -80)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(-20, -160)
    turtle.pendown()
    turtle.dot(15)
    turtle.penup()
    turtle.goto(30, -130)
    turtle.pendown()
    turtle.dot(15)

    time.sleep(4)
    #the dots starts to get connected
    turtle.penup()
    turtle.goto(-140, 50)
    turtle.pendown()
    turtle.goto(-140, 50)
    turtle.goto(-120, 90)
    turtle.goto(-200, 80)
    turtle.goto(-120, 90)
    turtle.goto(-100, 120)
    turtle.goto(-160, 20)
    turtle.goto(-220, -50)

    turtle.penup()
    turtle.goto(-220, 50)
    turtle.pendown()
    turtle.goto(-120, -80)
    turtle.goto(-100, -120)
    turtle.goto(-20, -160)
    turtle.penup()
    turtle.goto(30, -130)
    turtle.pendown()
    turtle.goto(-40, -80)
    turtle.goto(-120, -80)
    turtle.penup()
    turtle.goto(-120, 90)
    turtle.pendown()
    turtle.goto(20,50)
    turtle.goto(50,-20)
    turtle.penup()
    turtle.goto(20,50)
    turtle.pendown()
    turtle.goto(80,45)
    turtle.goto(120, 80)

    turtle.penup()
    turtle.goto(-300,250)
    turtle.pendown()
    turtle.write("The Gemini Constellation",font=("Courier",10,'italic'))
upgrade()
time.sleep(10)
window.clear()


